### ISSUE TITLE
BUG - when creating a dashboard , description should be required

### ISSUE THREAD

**Issue by mnischay** [awslabs/iot-application#1170]
![Screenshot 2023-09-06 at 3 05 06 PM](https://github.com/awslabs/iot-application/assets/135036199/e3b011ba-7a2b-47ec-9884-d6e29474f3e8)

steps to replicate 

1.  go to dashbaord 
2. create dashboard 
3. add a tittle name
4. click create button

### expectation
no error and dashboard should be created

**Comment by mnischay** [comment]
The criteria for this has changed, the text "optional" should be removed, the field is a REQUIRED field in the backend

**Comment by diehbria** [comment]
tracked in https://github.com/awslabs/iot-application/issues/1276
