### ISSUE TITLE
Dashboard state persist across to another dashboard incorrectly

### ISSUE THREAD

**Issue by chejimmy** [awslabs/iot-application#153]
**Describe the bug**

After saving widgets on a dashboard, the widgets would appear on another dashboard incorrectly.

**To Reproduce**

1. Go to */dashboards*
2. Click on *Create*, fill out the modal inputs, and proceed to create a dashboard
2. Click on newly created dashboard and add a widget
1. Go back to */dashboards*
2. Click on *Create*, fill out the modal inputs, and proceed to create another dashboard
2. Click on newly created dashboard
5. See a widget on the newly created dashboard
6. Refresh the page and the widget is no longer there

**Expected behavior**

the widget(s) state on the dashboard should reflect the select dashboard's configuration

**Screenshots**

https://user-images.githubusercontent.com/50635800/231851390-6973a07f-ec50-4931-85dd-b887af3fef2e.mov

**Desktop (please complete the following information):**

- OS: MacOS 13.2.1 (22D68)
- Browser Chrome
- Version Version 111.0.5563.64 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tracy-french** [comment]
Resolved in IoT App Kit. New version will be merged soon.
