### ISSUE TITLE
CloudFormation fails to deploy due to lack of Ec2InstanceRole

### ISSUE THREAD

**Issue by hartmir** [awslabs/iot-application#2163]
**Describe the bug**
Ec2InstanceRole cannot be found while deploying the CloudFormation template. `DeploymentEC2InstanceProfile` causes this error. `DeploymentEC2InstanceProfile` is cancelled.

**To Reproduce**

1. Download the CloudFormation template from the repository.
2. Go to CloudFormation AWS Console and deploy the template as-is.
3. Wait for the error to appear.

**Expected behavior**
Correct deployment of template.

**Screenshots**

![image](https://github.com/user-attachments/assets/cc41b473-d756-4404-820a-65eba54b3750)

**Desktop (please complete the following information):**

- OS: N/A, completed in AWS console
- Browser [e.g. chrome, safari]: Firefox
- Version [e.g. 22]: Commit #4f20198, HEAD of main as of making this issue

**Additional context**

**Comment by corteggiano** [comment]
We addressed the issue, please reopen if there are any other issues related to this.
