### ISSUE TITLE
[UX] Update icons for widget library

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-application#952]
Please reach out for SVGs

Refer -
Doc - https://quip-amazon.com/5U2EAtnId09B/Centurion-UX-Pre-GA
Design - https://www.figma.com/file/pmsbdMcD7ieVWRFMNxStIi/VoT--AppKit-%26-Centurion?type=design&node-id=348%3A423854&mode=design&t=1zPNBiyI9sH6mezN-1

**Comment by nadeswal** [comment]
![bar-graph](https://github.com/awslabs/iot-application/assets/141063047/8338b43e-c60f-4fc6-9e40-76a8ec79d4ba)
![kpi](https://github.com/awslabs/iot-application/assets/141063047/accf57fc-57c3-4622-b08e-5897633644d3)
![line-graph](https://github.com/awslabs/iot-application/assets/141063047/4a95ddc8-2144-43f0-80ce-9f619026a124)
![scatter-chart](https://github.com/awslabs/iot-application/assets/141063047/10fb8259-fb70-4973-9dc6-536136563689)
![table](https://github.com/awslabs/iot-application/assets/141063047/3ba07ba6-02a8-4f32-a3bd-01c1b5565529)
![text](https://github.com/awslabs/iot-application/assets/141063047/0d8c6e0b-c018-4724-a6af-e38a250157ca)
![timeline-graph](https://github.com/awslabs/iot-application/assets/141063047/03ae3040-e154-4888-bcbe-96f6ec955327)

**Comment by nadeswal** [comment]
Icon size - 40px
Padding between icons - 15px
Ignore the symbol icon for now

<img width="653" alt="Screenshot 2023-08-17 at 5 10 17 PM" src="https://github.com/awslabs/iot-application/assets/141063047/116f12b0-4103-4142-8e94-9635a38ab103">

**Comment by mnischay** [comment]
Make sure, to remove the status component when removing the status icon from above

**Comment by mnischay** [comment]
![Group 1223](https://github.com/awslabs/iot-application/assets/135036199/41a40a95-a395-4947-ac85-78afb18d43d3)

**Comment by Priyanshu44** [comment]
This is the same icon with padding as mentioned in previous comment by Navita. I need bar Icon with no padding like other icons.

**Comment by nadeswal** [comment]
![line-graph](https://github.com/awslabs/iot-application/assets/141063047/a8cb010d-e6f6-41a4-8747-6d919ddb6621)

**Comment by nadeswal** [comment]
![bar-graph](https://github.com/awslabs/iot-application/assets/141063047/0415fc7f-000f-44bf-a817-cd36e3b58527)

**Comment by nadeswal** [comment]
Updated the widget panel and removed the text.
Also, designed the hover state - fill the icon with Grey 600 on hover or let me know if you need SVGs for the hover state.

<img width="1332" alt="Screenshot 2023-08-23 at 12 35 11 PM" src="https://github.com/awslabs/iot-application/assets/141063047/e946f10a-f3ec-4c60-9350-071ea6ee8c5d">

**Comment by nadeswal** [comment]
![bar-graph](https://github.com/awslabs/iot-application/assets/141063047/00069a80-75e8-4380-a8db-1ae8b56f035c)
![kpi](https://github.com/awslabs/iot-application/assets/141063047/8de7d6e9-ac86-4628-a662-22e96c50a01f)
![line-graph](https://github.com/awslabs/iot-application/assets/141063047/7c01b0d5-704a-4ea1-b467-7a30157ad62b)
![scatter-chart](https://github.com/awslabs/iot-application/assets/141063047/273c18ab-e0af-4d54-b9a2-59db778bd898)
![status](https://github.com/awslabs/iot-application/assets/141063047/bae79db1-1f6f-4ef4-a90b-9445b57fc752)
![table](https://github.com/awslabs/iot-application/assets/141063047/6195049b-5923-4bbe-83c1-45f54abaea19)
![text](https://github.com/awslabs/iot-application/assets/141063047/e2101681-0294-4919-ac29-9bd1f07f01a3)
![timeline-graph](https://github.com/awslabs/iot-application/assets/141063047/a6bd15ec-6fe7-431f-92d3-c1b1d0d79b23)

Also, the cursor should change to drag in the hover state. 

Refer this screenshot -
<img width="1108" alt="Screenshot 2023-08-23 at 2 47 17 PM" src="https://github.com/awslabs/iot-application/assets/141063047/61304a62-53fb-45d3-97c6-e40d0bd041f3">
