### ISSUE TITLE
[UX] Auto collapse state for both panels

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-application#954]
Auto collapse state for both panels when no widget is selected

Refer -
Doc - https://quip-amazon.com/5U2EAtnId09B/Centurion-UX-Pre-GA
Design - https://www.figma.com/file/pmsbdMcD7ieVWRFMNxStIi/VoT--AppKit-%26-Centurion?type=design&node-id=348%3A423854&mode=design&t=1zPNBiyI9sH6mezN-1

**Comment by boweihan** [comment]
![Screenshot 2023-08-08 at 11 06 03 AM](https://github.com/awslabs/iot-application/assets/10264198/0d9ab4ba-c592-4cc2-89a1-214ec42d0802)

**Comment by nadeswal** [comment]
<img width="472" alt="Screenshot 2023-08-11 at 10 58 10 AM" src="https://github.com/awslabs/iot-application/assets/141063047/9a9e400f-33d6-40a9-a5b2-678e73835833">
