### ISSUE TITLE
[UX] Tile layout: Add asset properties

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-application#958]
Tile layout for informing users to add asset properties to the widget added to the canvas.

Refer -
Doc - https://quip-amazon.com/5U2EAtnId09B/Centurion-UX-Pre-GA
Design - https://www.figma.com/file/pmsbdMcD7ieVWRFMNxStIi/VoT--AppKit-%26-Centurion?type=design&node-id=348%3A423854&mode=design&t=1zPNBiyI9sH6mezN-1

**Comment by diehbria** [comment]
duplicate https://github.com/awslabs/iot-app-kit/issues/1919
